#!/usr/bin/env bash

set -e
set -u
set -o pipefail

declare -r haproxy_config='/usr/local/etc/haproxy/haproxy.cfg'

terraform init
terraform apply -auto-approve
cp haproxy.cfg "$haproxy_config"
haproxy -c -f "$haproxy_config"
